version: v5

enhancement
- all
  - base-branch: ['feat']
  - changed-files:
    - any-glob-to-any-file: ['packages/fluent-editor/src/**']
documentation
- changed-files:
  - any-glob-to-any-file: ['packages/docs/**', 'packages/projects/**', '!packages/docs/**/*.spec.ts']
bug
- all
  - base-branch: ['fix']
  - changed-files:
    - any-glob-to-any-file: ['packages/fluent-editor/src/**']
ci
- changed-files:
  - any-glob-to-any-file: ['.github/**']
e2e-test
- changed-files:
    - any-glob-to-any-file: ['packages/docs/**/*.spec.ts']
v3
- head-branch: ['main']
v4
- head-branch: ['v4']
