version: v1

labels:
  - label: 'enhancement'
    sync: true
    matcher:
      title: '^feat:.*'
  - label: 'documentation'
    sync: true
    matcher:
      title: '^docs:.*'
  - label: 'documentation'
    sync: true
    matcher:
      title: '^chore:.*'
  - label: 'bug'
    sync: true
    matcher:
      title: '^fix:.*'
  - label: 'ci'
    sync: true
    matcher:
      title: '^ci:.*'
  - label: 'e2e-test'
    sync: true
    matcher:
      title: '^test:.*'
