name: autofix.ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  merge_group: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm lint --fix

      - uses: autofix-ci/action@v1.3
